labs11-studentdata/labs11-studentData-FE

src/components/OnBoardingCards.js
src/components/OnboardingPage.js
src/components/index.js
src/index.js

Just 2 react components for the onboarding view
new files
- [ maybe?] New feature (non-breaking change which adds functionality)
- [ x] Complete, tested, ready to review and merge
- [x ] My changes generate no new warnings
- [x ] There are no merge conflicts

Created base view for the onboarding page

---

src/components/OnboardingPage.js
src/index.js

Description
Added the route for the onboarding page to the main index page
Type of change
changed the main index slightly
[ maybe?] New feature (non-breaking change which adds functionality)
Change Status
[ x] Complete, tested, ready to review and merge
Complete, but not tested (may need new tests)
Incomplete/work-in-progress, PR is for discussion/feedback
How Has This Been Tested?
opened in react Test A
Test B
Checklist
My code follows the style guidelines of this project
I have performed a self-review of my own code
My code has been reviewed by at least one peer
I have commented my code, particularly in hard-to-understand areas
I have made corresponding changes to the documentation
[x ] My changes generate no new warnings
I …

added the routes for the onboarding page to the main index page

---

src/App.js
src/components/Header/HeaderComponent.js
src/components/HeaderComponent.js
src/components/SponsorAChild/SponsorChildComponent.js
src/components/VisitLog.js
src/components/index.js
src/index.js
src/styles/LoginStyles.css
src/views/HeaderView.js
src/views/SponsorChildView.js
src/views/index.js

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- [x ] New feature (non-breaking change which adds functionality)

Leianne louis

---

src/components/SponsorAChild/SimpleModel.js
src/components/SponsorAChild/SponsorAChild.css
src/components/SponsorAChild/SponsorChildComponent.js
src/views/SponsorChildView.js

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

added mock data for sponsor child view

---

src/components/Payment/PaymentComponent.js
src/components/SponsorAChild/SponsorChildComponent.js
src/views/SponsorChildView.js

Allows for users to pull from local api

 now pulling data from local api

---

src/components/SponsorAChild/SponsorChildComponent.js
src/views/SponsorChildView.js

Changed the server to the deployed api

changed the server to the deployed api

---

src/components/BoardMember/StudentTable.js
src/reducers/StudentReducer.js
src/reducers/index.js
src/views/BoardDashboard.js

Refactored the redux organization before it gets too out of hand

---

.env
src/actions/index.js
src/components/SchoolSelect.js
src/components/index.js
src/reducers/SchoolReducer.js
src/reducers/VisitReducer.js
src/reducers/index.js
src/views/BoardDashboard.js

improved redux flow(optional) and added a school/grade selector component

---

src/actions/index.js
src/components/BoardMember/SmallSponsor.js
src/components/BoardMember/StudentTable.js
src/components/index.js
src/views/BoardView.js
src/views/index.js

Light sponsorship component modal in board member view

---

package.json

Moved proxy to netlify deploy

---

src/components/StudentView/AddStudent.js
src/components/StudentView/DeleteStudent.js
src/components/index.js
src/views/StudentView.js

basic delete student component added

basic delete student component added

---

src/login/LoginComponent.js

changed the static local host to .env

added create a school boiler plate

---

src/App.js
src/actions/login.js
src/index.js
src/login/LoginView.js

Made changes to index.js and how routes are being called to authenticate and send user to onboarding

changed front end routing to match BE deployment

---

src/components/CreateASchool/CreateASchoolForm.js
src/components/Header/HeaderComponent.js
src/components/Onboarding/OnboardingPage.js
src/index.js
src/views/BoardView.js
src/views/SponsorChildView.js
src/views/StudentView.js

Added create a student form and also added in nav links to display connecting views

added header to views and added Create school form

---

src/App.js

Resolved merge conflict in app.js

Resolved merge conflict in app.js

---

src/index.js

Added social worker and admin views to index routes

---

src/components/SocialWorker/addVisit.js
src/components/SocialWorker/deleteVisitButton.js
src/components/SocialWorker/singleVisit.js
src/components/SocialWorker/updateVisit.js

Updates URLs in visits endpoints to environment variables.

Updates URLs in visits endpoints.

---

src/actions/index.js
src/views/AdminDashboard.js
src/views/BoardView.js
src/views/SocialWorkerView.js

Hooking up redux

---

src/views/DashboardFrame.js

Dashboard framework with grid

---

src/views/BoardView.js
src/views/DashboardFrame.js

Plugged in dashboard frame.

---

src/components/StudentView/AddStudentModal.js
src/components/StudentView/EditStudentModal.js
src/components/index.js
src/views/AdminDashboard.js
src/views/StudentView.js

changed add and edit student components to be modals

changed add and edit student components to be modals

---

src/components/StudentView/AddStudent.js
src/components/StudentView/AddStudentModal.js
src/components/StudentView/EditStudent.js
src/components/StudentView/EditStudentModal.js
src/views/StudentView.js

add and edit student modals working

add and edit student modals working

---

README.md
src/components/BoardMember/HighestDues.js
src/components/SchoolSelect.js
src/views/BoardView.js
src/views/DashboardFrame.js

Created HighestDues component for Board footer.

---

src/views/SocialWorkerDashboard.js

social worker dashboard now gets all notes posted by the user

social worker dashboard now gets all notes posted by the user

---

src/views/SocialWorkerDashboard.js
src/views/StudentView.js

-added placeholder for individual notes view and social worker dashboard now links to sponsor page
-added temp fix for deleting a student

added placeholder for individual notes view and social worker dashboard now links to sponsor page

---

src/components/BoardMember/HighestDues.js
src/components/Header/HeaderComponent.js
src/views/BoardView.js

Fixes # board footer component crashing site when students filtered > 0 and < 5
Simplified nav, centered, and set max width container to 1300

Fix top5 bug, simplified navbar

---

src/actions/index.js
src/components/BoardMember/StudentTable.js
src/components/SchoolSelect.js
src/components/Stripe/StripeComponent.js
src/views/BoardView.js

Enabled conditional filter tool and stripe now adds donations to the table record

---

src/components/BoardMember/HighestDues.js
src/components/BoardMember/StudentTable.js
src/components/Stripe/StripeComponent.js
src/views/BoardView.js

Fixes # Cleans up Stripe form(still needs work), adds donation button to table, removes "enrollment status" column from table, wires up the donation button in the Highest Dues tracker

Improved Stripe interface

---

src/components/SchoolSelect.js
src/views/SocialWorkerView.js

Fixes # Added more input labels and hooked the filter up to old SW view for Josh to reference

Tweaking updated filter and hooking it up to old social worker view for reference

---

src/components/SchoolSelect.js
src/components/SocialWorker/addVisit.js
src/components/SocialWorker/deleteVisitButton.js
src/components/SocialWorker/updateVisit.js
src/components/SponsorAChild/SimpleModel.js
src/components/SponsorAChild/SponsorChildComponent.js
src/components/StudentView/AddStudent.js
src/components/StudentView/AddStudentModal.js
src/components/StudentView/EditStudent.js
src/components/StudentView/EditStudentModal.js
src/views/BoardView.js
src/views/DashboardFrame.js
src/views/StudentView.js

Updates buttons site wide. Add second body to dash

---

package-lock.json
package.json
src/App.js
src/components/ImageUpload/ImageUpload.js
src/components/StudentView/EditStudent.js
src/views/SocialWorkerDashboard.js
src/views/StudentView.js

basic front end image upload component added

basic front end image upload component added

---

src/components/ImageUpload/ImageUpload.js

fixed frontend for image uploads

fixed frontend for image uploads

---

src/views/BoardView.js

Switches board dash left nav links to be onClick setState. Then added a switch statement to change the body components based on the state.

Change board body to switch on state

---

src/App.js
src/components/SponsorAChild/SponsorChildComponent.js
src/components/StudentView/EditStudent.js
src/views/SocialWorkerDashboard.js
src/views/StudentView.js

updated edit student, individual student, and delete student frontend

updated edit student, individual student, and delete student frontend

---

src/actions/index.js
src/components/BoardMember/HighestDues.js
src/components/BoardMember/StudentRow.js
src/components/BoardMember/StudentTable.js
src/components/SchoolSelect.js
src/components/SponsorAChild/SponsorChildComponent.js
src/components/Stripe/StripeComponent.js
src/views/BoardView.js
src/views/SponsorChildView.js

Updated names/fixed dues display. May have broken Highest Dues, will fix after lunch

---

src/actions/login.js
src/components/CreateASchool/CreateASchoolForm.js
src/components/Header/HeaderComponent.js
src/components/Onboarding/OnboardingView.css
src/components/Onboarding/OnboardingView.js
src/components/Schools/SchoolList.js
src/components/StudentView/AddStudent.js
src/components/StudentView/EditStudent.js
src/components/StudentView/EditStudentModal.js
src/components/StudentView/StudentStyles.css
src/reducers/LoginReducer.js
src/views/AdminDashboard/AdminChildComponent.js
src/views/AdminDashboard/AdminDashboard.css
src/views/AdminDashboard/AdminDonationList.js
src/views/AdminDashboard/AdminSchoolListComp.js
src/views/AdminDashboard/AdministratorDash.js
src/views/DashboardFrame.js

Updates the onboarding flow for all users also update the admin dashboard with updated data schema

Updates the onboarding flow for all users also update the admin dashboard with updated data schema

---

src/views/SocialWorkerDashboard.js

updated social worker dashboard to use a seeded sample user with social worker visits attached

updated social worker dashboard to use a seeded sample user with social worker visits attached

---

.gitignore
src/components/CreateASchool/CreateASchoolForm.js
src/components/Onboarding/OnboardAccount.js
src/components/Onboarding/OnboardingView.css
src/components/Onboarding/OnboardingView.js
src/components/Schools/SchoolList.js
src/views/AdminDashboard/AdminChildComponent.js
src/views/AdminDashboard/AdminDashboard.css
src/views/AdminDashboard/AdminSchoolListComp.js
src/views/DashboardFrame.js

Updates the admin view and onboarding view to meet UI needs

Updates the admin view and onboarding view to meet UI needs

---

src/components/SocialWorker/addVisit.js
src/styles/VisitsStyles.css
src/views/Visits.js

Description
some updates to the visits page, still having issues connecting to the backend
Type of change
x New feature (non-breaking change which adds functionality)
Change Status
x  Complete, tested, ready to review and merge
How Has This Been Tested?
x Test locally
Checklist
x  My code follows the style guidelines of this project
x  I have performed a self-review of my own code
My code has been reviewed by at least one peer
x  I have commented my code, particularly in hard-to-understand areas
I have made corresponding changes to the documentation
x My changes generate no new warnings
I have added tests that prove my fix is effective or that my feature works
New and existing unit tests pass locally with my changes
x There are no merge …

updated visits page

---

package-lock.json
package.json
src/views/AdminDashboard/AdminChildComponent.js
src/views/AdminDashboard/AdminDashboard.css
src/views/AdminDashboard/AdminSchoolListComp.js
src/views/AdminDashboard/AdministratorDash.js

Fixes # Stripped out the native MUI padding from the big table and manually set the column widths by percentage, column names should no longer require explainers

Recommended UI improvement for My Students admin view table

---

src/components/BoardMember/BoardSocial.js
src/components/BoardMember/BoardSocialSchoolSelect.js
src/components/SponsorAChild/SponsorChildCard.js
src/components/SponsorAChild/SponsorChildComponent.js
src/views/DashboardFrame.js

Removed clickable area on child card.
Centered students on sponsor page
Fixed scrolling issues, extra scroll bar
Adjusted some heading sizes and positioning

Many styling tweaks

---

src/components/Header/HeaderComponent.js
src/components/LandingPage/LandingCardBtn.js
src/components/StudentView/AddStudent.js
src/components/StudentView/EditStudent.js
src/components/StudentView/StudentStyles.css
src/login/LoginView.js
src/views/LandingPage.js

Updated the loading and sign up page also the admin page data

Updated the loading and sign up page also the admin page data

---

src/styles/LandingPage.css
src/views/LandingPage.js

Fixed a deleted line of code in the last PR

replaced deleted code

---

package.json
src/auth/requiresAuth.js
src/components/BoardMember/BoardSocialSchoolSelect.js
src/components/CreateASchool/CreateASchoolForm.js
src/components/LandingPage/RoleCard.js
src/components/StudentView/AddStudent.js
src/components/StudentView/EditStudent.js
src/index.js
src/login/LoginView.js
src/views/AdminDashboard/AdminSchoolListComp.js
src/views/AdminDashboard/AdministratorDash.js
src/views/BoardView.js
src/views/LandingPage.js

Fixes
package.json updated proxy
src/auth/requiresAuth.js removed unused import
src/components/BoardMember/BoardSocialSchoolSelect.js remove duplicate margin and useless constructor
src/components/CreateASchool/CreateASchoolForm.js remove unused Component import
src/components/LandingPage/RoleCard.jschanged role prop to userRole since role is html reserved
src/components/StudentView/AddStudent.js removed unused imports
src/components/StudentView/EditStudent.js remove unused import and duplicate class
src/views/AdminDashboard/AdministratorDash.js removed unused variables
src/views/BoardView.js removed unreachable `break` statements

Removed unused imports.

---

src/App.js
src/actions/login.js
src/components/BoardMember/HighestDues.js
src/components/BoardMember/StudentTable.js
src/components/Header/HeaderComponent.js
src/components/ImageUpload/ImageUpload.js
src/components/Onboarding/OnboardAccount.js
src/components/Onboarding/OnboardingForm.js
src/components/SchoolSelect.js
src/components/SocialWorker/addVisit.js
src/components/SponsorAChild/SponsorChildCard.js
src/components/SponsorAChild/SponsorChildComponent.js
src/components/StudentView/AddStudentModal.js
src/components/StudentView/EditStudentModal.js
src/reducers/AdminReducer.js
src/views/AdminDashboard/AdminChildComponent.js
src/views/DashboardFrame.js
src/views/SocialWorkerDashboard.js
src/views/SponsorChildView.js
src/views/StudentView.js

Removed more unused imports and cleared errors

Removed more unused imports and cleared errors

---

src/components/LandingPage/PromoCard.js
src/styles/LandingPage.css
src/views/LandingPage.js

Description
Finished the styling for the Landing page.
Type of change
x New feature (non-breaking change which adds functionality)
Change Status
x Complete, tested, ready to review and merge
How Has This Been Tested?
x Test locally
Checklist
x My code follows the style guidelines of this project
x I have performed a self-review of my own code
My code has been reviewed by at least one peer
x I have commented my code, particularly in hard-to-understand areas
I have made corresponding changes to the documentation
x My changes generate no new warnings
I have added tests that prove my fix is effective or that my feature works
New and existing unit tests pass locally with my changes
x There are no merge conflicts

Josh tietz

---

src/App.js
src/components/Header/HeaderComponent.js
src/components/Onboarding/OnboardingForm.js
src/components/StudentView/AddStudent.js
src/components/StudentView/EditStudent.js
src/views/HeaderView.js
src/views/MyAccount/MyAccountForm.js

Cleaned unused imports and simple errors.

---

src/views/SocialWorkerDashboard.js

updated social worker dashboard

updated social worker dashboard

---

src/components/Stripe/StripeComponent.js
src/reducers/StripeReducer.js
src/reducers/StudentReducer.js

Improved donation fail state

---

src/components/BoardMember/HighestDues.js
src/views/BoardView.js
src/views/SponsorChildView.js
src/views/Visits.js

Fixed userID references

---

README.md
src/App.js
src/components/Redirect/Redirect.js

Made redirect component for web root

---

src/components/Header/HeaderComponent.js

Linked navbar logo to web root

---

src/components/LandingPage/PromoCard.js
src/styles/LandingPage.css
src/views/LandingPage.js

Styling/typo fixes for landing page.

Styling/typo fixes for landing page.
